name: Build and deploy Node.js + React app to Azure Web App - onlineshoppingcart

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd front-end
          npm ci

      # Build frontend
      - name: Build frontend
        run: |
          cd front-end
          npm run build

      # Copy frontend build into backend
      - name: Copy frontend build into backend
        run: |
          rm -rf back-end/dist
          cp -r front-end/dist back-end/dist

      # Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd back-end
          npm ci

      # Upload backend artifact
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./back-end

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./back-end

      - name: Install backend dependencies in deploy job
        run: |
          cd back-end
          npm ci

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_20567C9116EE43C9807F0CC2D7602EE0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_84D6F992D3DA4CEA90A2352BF75CDA2E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_04294473C65048C8A7EA9C6B0E7E26ED }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'onlineshoppingcart'
          slot-name: 'Production'
          package: ./back-end
